### ISSUE TITLE
wrong-type-argument error occured

### ISSUE THREAD

**Issue by takuborn** [kiwanami/emacs-id-manager#10]
I run into the following error after upgrading emacs from 25.2 to 25.3.
It seems like failed to read the gpg file.
How can I resolve this problem?
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  file-truename(nil)
  find-file-noselect-1(#<buffer .idm-db.gpg<15>> "~/.idm-db.gpg" nil nil "~/.idm-db.gpg" (30332234 16777218))
  find-file-noselect("/Users/takuma/.idm-db.gpg")
  idm-load-db()
  id-manager()
  funcall-interactively(id-manager)
  call-interactively(id-manager nil nil)
  command-execute(id-manager)
```

I tried to run byte-compile-file for id-manage.el in new emacs version, but not work...

environments: 
* Mac OS Sierra
* Emacs 25.3 (In 25.2 no problem)

**Comment by kiwanami** [comment]
I'm so sorry for my slow response.
Well, I compiled emacs 25.3 and checked it, but I could not reproduced the problem.

``` 
GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.19) of 2017-12-06
gpg (GnuPG) 2.2.0
libgcrypt 1.8.1
```
Will you try to just open a gpg file, not using id-manager?

**Comment by takuborn** [comment]
Thanks for your reply.
I'd tried to decrypt gpg file using gpg command and failed to decrypt.
So, id-manager is unrelated.

I'm sorry...

**Comment by kiwanami** [comment]
Thank you for your confirmation!
Hmm, failure in decryption looks more serious...
