### ISSUE TITLE
password generator function should allow elisp

### ISSUE THREAD

**Issue by hexmode** [kiwanami/emacs-id-manager#4]
This would allow people to use http://github.com/zargener/emacs-password-genarator if they wanted.

**Comment by kiwanami** [comment]
Hi, @hexmode 
I'm sorry for my late response.

I added the function at 0d968929bbaff813dd7e098c7f69e0b54434ce09.
You can use some function of emacs-password-generator like this: 

```
(setq idm-gen-password-cmd (lambda () (password-generator-simple 12 t)))
```

Thank you.

**Comment by hexmode** [comment]
Thanks! 

----- Original Message -----

> Hi, @hexmode
> I'm sorry for my late response.

> I added the function at 0d96892 .
> You can use some function of emacs-password-generator like this:
> (setq idm-gen-password-cmd (lambda () (password-generator-simple 12 t)))

> Thank you.

> —
> Reply to this email directly or view it on GitHub .

-- 
Mark A. Hershberger 
NicheWork LLC 
717-271-1084
